name: Deploy Website Acessível

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Verificar Sintaxe do HTML
      run: |
        sudo apt-get install -y html-validator
        html-validator index.html

    - name: Deploy para GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Diretório onde o index.html está localizado
